//
// Autogenerated by Thrift Compiler (0.17.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
const thrift = require('thrift');
const Thrift = thrift.Thrift;
const Int64 = require('node-int64');


const ttypes = module.exports = {};
if (typeof tutorial === 'undefined') {
  tutorial = {};
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports.tutorial = tutorial;
}
