//
// Autogenerated by Thrift Compiler (0.17.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = module.exports = {};
if (typeof tutorial === 'undefined') {
  tutorial = {};
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports.tutorial = tutorial;
}
